In [2]:
import requests

base_url = "https://quotes.toscrape.com/page/"

# Loop through the first 3 pages
for i in range(1, 4):
  url = f"{base_url}{i}/"
  response = requests.get(url)

  # Print the HTML content for each page (optional, can be removed if not needed)
  print(f"--- Content for page {i} ---")
  print(response.text[:500]) # Print first 500 characters to avoid flooding output

  # Save the HTML content to a file
  with open (f"/content/sample_data/page{i}.html", "w") as f:
    f.write (response.text)
  print(f"Saved page {i} to /content/sample_data/page{i}.html")

--- Content for page 1 ---
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">


</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div cla
Saved page 1 to /content/sample_data/page1.html
--- Content for page 2 ---
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">


</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div cla
Saved page 2 to /content/sample_data/page2.html
--- Content for page 3 ---
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">


</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div cla
Saved page 3 to /content/sample_data/page3.html

In [14]:
from bs4 import BeautifulSoup

all_authors = []

for i in range(1, 4): # Loop through pages 1, 2, 3
  file_path = f"/content/sample_data/page{i}.html"
  try:
    with open(file_path, "r") as f:
      content = f.read()

    soup = BeautifulSoup(content, "html.parser")
    author_elements = soup.find_all("small", class_="author")

    print(f"--- Authors from page {i} ---")
    for author_tag in author_elements:
      author_name = author_tag.get_text()
      print(author_name)
      all_authors.append(author_name)
  except FileNotFoundError:
    print(f"File not found: {file_path}")
  except Exception as e:
    print(f"An error occurred while processing {file_path}: {e}")

print("\n--- All unique authors found ---")
unique_authors = sorted(list(set(all_authors)))
for author in unique_authors:
  print(author)

print(f"\nTotal unique authors found: {len(unique_authors)}")

--- Authors from page 1 ---
Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe
Albert Einstein
André Gide
Thomas A. Edison
Eleanor Roosevelt
Steve Martin
--- Authors from page 2 ---
Marilyn Monroe
J.K. Rowling
Albert Einstein
Bob Marley
Dr. Seuss
Douglas Adams
Elie Wiesel
Friedrich Nietzsche
Mark Twain
Allen Saunders
--- Authors from page 3 ---
Pablo Neruda
Ralph Waldo Emerson
Mother Teresa
Garrison Keillor
Jim Henson
Dr. Seuss
Albert Einstein
J.K. Rowling
Albert Einstein
Bob Marley

--- All unique authors found ---
Albert Einstein
Allen Saunders
André Gide
Bob Marley
Douglas Adams
Dr. Seuss
Eleanor Roosevelt
Elie Wiesel
Friedrich Nietzsche
Garrison Keillor
J.K. Rowling
Jane Austen
Jim Henson
Marilyn Monroe
Mark Twain
Mother Teresa
Pablo Neruda
Ralph Waldo Emerson
Steve Martin
Thomas A. Edison

Total unique authors found: 20

In [20]:
all_tags = []

for i in range(1, 4): # Loop through pages 1, 2, 3
  file_path = f"/content/sample_data/page{i}.html"
  try:
    with open(file_path, "r") as f:
      content = f.read()

    soup = BeautifulSoup(content, "html.parser")
    # Find all 'div' elements with class 'tags'
    tags_div_elements = soup.find_all("div", class_="tags")

    print(f"--- Tags from page {i} ---")
    for tags_div in tags_div_elements:
      # Within each 'tags_div', find all 'a' elements with class 'tag'
      tag_elements = tags_div.find_all("a", class_="tag")
      for tag_element in tag_elements:
        tag_name = tag_element.get_text()
        print(tag_name)
        all_tags.append(tag_name)
  except FileNotFoundError:
    print(f"File not found: {file_path}")
  except Exception as e:
    print(f"An error occurred while processing {file_path}: {e}")

print("\n--- All unique tags found ---")
unique_tags = sorted(list(set(all_tags)))
for tag in unique_tags:
  print(tag)

print(f"\nTotal unique tags found: {len(unique_tags)}")

--- Tags from page 1 ---
change
deep-thoughts
thinking
world
abilities
choices
inspirational
life
live
miracle
miracles
aliteracy
books
classic
humor
be-yourself
inspirational
adulthood
success
value
life
love
edison
failure
inspirational
paraphrased
misattributed-eleanor-roosevelt
humor
obvious
simile
--- Tags from page 2 ---
friends
heartbreak
inspirational
life
love
sisters
courage
friends
simplicity
understand
love
fantasy
life
navigation
activism
apathy
hate
indifference
inspirational
love
opposite
philosophy
friendship
lack-of-friendship
lack-of-love
love
marriage
unhappy-marriage
books
contentment
friends
friendship
life
fate
life
misattributed-john-lennon
planning
plans
--- Tags from page 3 ---
love
poetry
happiness
attributed-no-source
humor
religion
humor
comedy
life
yourself
children
fairy-tales
imagination
music

--- All unique tags found ---
abilities
activism
adulthood
aliteracy
apathy
attributed-no-source
be-yourself
books
change
children
choices
classic
comedy
contentment
courage
deep-thoughts
edison
failure
fairy-tales
fantasy
fate
friends
friendship
happiness
hate
heartbreak
humor
imagination
indifference
inspirational
lack-of-friendship
lack-of-love
life
live
love
marriage
miracle
miracles
misattributed-eleanor-roosevelt
misattributed-john-lennon
music
navigation
obvious
opposite
paraphrased
philosophy
planning
plans
poetry
religion
simile
simplicity
sisters
success
thinking
understand
unhappy-marriage
value
world
yourself

Total unique tags found: 60

In [23]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Install openpyxl if not already installed, as it's needed by pandas for .xlsx files
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [24]:
all_quotes_data = []

for i in range(1, 4): # Loop through pages 1, 2, 3
  file_path = f"/content/sample_data/page{i}.html"
  try:
    with open(file_path, "r") as f:
      content = f.read()

    soup = BeautifulSoup(content, "html.parser")

    # Find all quote containers on the page
    quote_divs = soup.find_all("div", class_="quote")

    for quote_div in quote_divs:
      # Extract quote text
      quote_text = quote_div.find("span", class_="text").get_text()

      # Extract author
      author = quote_div.find("small", class_="author").get_text()

      # Extract tags (multiple tags per quote)
      tags_elements = quote_div.find("div", class_="tags").find_all("a", class_="tag")
      tags = [tag.get_text() for tag in tags_elements]

      all_quotes_data.append({"Quote": quote_text, "Author": author, "Tags": ", ".join(tags)})

  except FileNotFoundError:
    print(f"File not found: {file_path}")
  except Exception as e:
    print(f"An error occurred while processing {file_path}: {e}")

# Create a pandas DataFrame
df_quotes = pd.DataFrame(all_quotes_data)

# Save the DataFrame to an Excel file
excel_file_path = "quotes_data.xlsx"
df_quotes.to_excel(excel_file_path, index=False)

print(f"Successfully created Excel file: {excel_file_path}")
display(df_quotes.head())

Successfully created Excel file: quotes_data.xlsx

,Quote,Author,Tags
0,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices"
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational"

In [3]:
from bs4 import BeautifulSoup
with open ("/content/sample_data/page1.html") as f:
  content = f.read()

In [4]:
soup = BeautifulSoup(content, "html.parser")

In [11]:
author_elements = soup.find_all("small", class_="author")

In [12]:
author_elements

[<small class="author" itemprop="author">Albert Einstein</small>,
 <small class="author" itemprop="author">J.K. Rowling</small>,
 <small class="author" itemprop="author">Albert Einstein</small>,
 <small class="author" itemprop="author">Jane Austen</small>,
 <small class="author" itemprop="author">Marilyn Monroe</small>,
 <small class="author" itemprop="author">Albert Einstein</small>,
 <small class="author" itemprop="author">André Gide</small>,
 <small class="author" itemprop="author">Thomas A. Edison</small>,
 <small class="author" itemprop="author">Eleanor Roosevelt</small>,
 <small class="author" itemprop="author">Steve Martin</small>]

In [13]:
for author_tag in author_elements:
  print(author_tag.get_text())

Albert Einstein
J.K. Rowling
Albert Einstein
Jane Austen
Marilyn Monroe
Albert Einstein
André Gide
Thomas A. Edison
Eleanor Roosevelt
Steve Martin

In [21]:
tags_divs = soup.find_all("div", class_="tags")
tag_elements = []
for tags_div in tags_divs:
    tag_elements.extend(tags_div.find_all("a", class_="tag"))

In [22]:
for tag_element in tag_elements:
  print(tag_element.get_text())

love
poetry
happiness
attributed-no-source
humor
religion
humor
comedy
life
yourself
children
fairy-tales
imagination
music

In [26]:
df = pd.read_excel("/content/quotes_data.xlsx")

In [28]:
df.head(10)

,Quote,Author,Tags
0,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices"
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational"
5,“Try not to become a man of success. Rather be...,Albert Einstein,"adulthood, success, value"
6,“It is better to be hated for what you are tha...,André Gide,"life, love"
7,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"edison, failure, inspirational, paraphrased"
8,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,misattributed-eleanor-roosevelt
9,"“A day without sunshine is like, you know, nig...",Steve Martin,"humor, obvious, simile"